services:
  db:
    image: levis38/postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_EXPOSE}
    volumes:
      - data:/var/lib/postgresql
    networks:
      - my-net
  api:
    image: levis38/home-library-api:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - my-net

volumes:
  data:
networks:
  my-net: